image: peterzuger/arch-dev

stages:
  - prepare
  - prebuild
  - build
  - test

# global variables
variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/bitstruct

fetch-micropython:
  stage: prepare
  script:
    - git clone --recurse-submodules https://github.com/micropython/micropython.git
  artifacts:
    paths:
      - micropython/

mpy-cross:
  stage: prebuild
  script:
    - make -C micropython/mpy-cross
  artifacts:
    paths:
      - micropython/mpy-cross/mpy-cross
  dependencies:
    - fetch-micropython

unix:
  stage: build
  script:
    - make -C micropython/ports/unix USER_C_MODULES=$CI_BUILDS_DIR CFLAGS_EXTRA="-DMODULE_BITSTRUCT_ENABLED=1"
  artifacts:
    paths:
      - micropython/ports/unix/micropython
  dependencies:
    - mpy-cross
    - fetch-micropython

stm32:
  stage: build
  script:
    - make -C micropython/ports/stm32 USER_C_MODULES=$CI_BUILDS_DIR CFLAGS_EXTRA="-DMODULE_BITSTRUCT_ENABLED=1"
  dependencies:
    - mpy-cross
    - fetch-micropython
